apiVersion: v1
kind: Secret
metadata:
  namespace: prometheus
  name: alertmanager-kube-prometheus-stack-alertmanager
  labels:
    release: kube-prometheus-stack
type: Opaque
stringData:
  alertmanager.yaml: |
      global:
        resolve_timeout: 5m
      route:
        group_by:
          - alertname
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: slack-notifications
        routes:
        - receiver: slack-notifications
          match:
            severity: critical
      receivers:
      - name: slack-notifications
        slack_configs:
        - channel: "#registration-service-notifications"
          send_resolved: true
          api_url: "https://hooks.slack.com/services/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"
          text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"