apiVersion: v1
kind: Secret
metadata:
  namespace: prometheus
  name: alertmanager-kube-prometheus-stack-alertmanager
  labels:
    release: kube-prometheus-stack
type: Opaque
stringData:
  alertmanager.yaml: |
      global:
        resolve_timeout: 5m
      inhibit_rules:
      - equal:
        - namespace
        - alertname
        source_matchers:
        - severity = critical
        target_matchers:
        - severity =~ warning|info
      - equal:
        - namespace
        - alertname
        source_matchers:
        - severity = warning
        target_matchers:
        - severity = info
      - equal:
        - namespace
        source_matchers:
        - alertname = InfoInhibitor
        target_matchers:
        - severity = info
      route:
        group_by:
          - namespace
          - severity
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: "null"
        routes:
        - receiver: registration-service-slack
          match:
            alertname: RegistrationHighCPUUsage
        - receiver: registration-service-slack
          match:
            alertname: RegistrationDeploymentDown
      receivers:
      - name: "null"
      - name: registration-service-slack
        slack_configs:
        - channel: "#registration-service-notifications"
          send_resolved: true
          api_url: "https://hooks.slack.com/services/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"
          text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"